project_id = "jiragtersejnarxruqyd"

[functions.send-appointment-notification]
verify_jwt = false

[functions.process-appointment-reminders]
verify_jwt = false

[functions.process-birthday-messages]
verify_jwt = false
