project_id = "jiragtersejnarxruqyd"

[functions.process-agenda-pro-reminders]
verify_jwt = false

[functions.send-appointment-notification]
verify_jwt = false

[functions.agenda-pro-notification]
verify_jwt = false

[functions.process-appointment-reminders]
verify_jwt = false

[functions.process-birthday-messages]
verify_jwt = false

[functions.tray-commerce-api]
verify_jwt = false

[functions.tray-commerce-webhook]
verify_jwt = false

[functions.widget-messages]
verify_jwt = false

[functions.auto-reconnect-instances]
verify_jwt = false

[functions.agenda-pro-confirmation]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.generate-payment-link]
verify_jwt = false

[functions.cleanup-orphan-lawfirm]
verify_jwt = false

[functions.process-trial-reminders]
verify_jwt = false

[functions.process-task-due-alerts]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
