project_id = "jiragtersejnarxruqyd"

[functions.evolution-api]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false

[functions.n8n-callback]
verify_jwt = false

[functions.n8n-trigger]
verify_jwt = true
